### ISSUE TITLE
Planning / Sample Data Survey

### ISSUE THREAD

**Issue by chadfawcett** [KamloopsR/Meetup#1]
I've created a short survey to help plan when to have the re-occurring meetup. There are also questions that will be used to create a local/relevant dataset to experiment with.

Is there anything else worth adding?
https://goo.gl/forms/vT69l33LHZLyioQw2

**Comment by stefaniebutland** [comment]
Thanks for creating this @chadfawcett - looks really good!
- I filled the survey so you'd have a sample - I can re-fill later if you make changes
- for "What time[s] of day are you free to attend?", add..."for 1.5 to 2hrs" or make times 5:30-7:00, 6:00-8:00 etc
- To help with answering some questions, perhaps in the intro text say we're aiming to have a group commit to 4 -5 weeks of meetups of 1.5 - 2hrs each time and if interest persists for some, we'll decide how to continue, or under "How frequently would you like to meet?
- "please keep an eye on the #r-meetup slack channel for updates." -> Please join the "Built in Kamloops Slack workspace (https://builtinkamloops-slackin.now.sh/) and keep an eye on the #r-meetup slack channel for updates."

**Comment by chadfawcett** [comment]
Thanks for the feedback @stefaniebutland! I've implemented your suggestions. Feel free to start sharing the survey if you think it's good to go!
