### ISSUE TITLE
Useful learning resource list

### ISSUE THREAD

**Issue by chadfawcett** [KamloopsR/Meetup#3]
Create a living document of helpful resources to learn R. This could either be done in the README, a separate markdown file, or as part of the Wiki.

My suggestion would be to start with either the README, or separate markdown file to begin with. We could migrate it to the Wiki if we get more and more documents started.

**Comment by kluft** [comment]
Added a few more resources to the one @stefaniebutland created, let me know if either of you has comments or thoughts on the format or content.
