### ISSUE TITLE
Meetup.com Account

### ISSUE THREAD

**Issue by chadfawcett** [KamloopsR/Meetup#4]
Would this meetup benefit from an account on Meetup.com? Communicating with attendees, event reminders, event discovery, etc?

**Comment by stefaniebutland** [comment]
response from Kasey: "looks like you have pay a monthly subscription to host a meetup group. That is very unfortunate. $10 US/month for a basic subscription or $14 US/month for an unlimited subscription"

Beth said that they use Eventbrite and Facebook events but we decided there's not enough value for us to use these right now e.g. People will often RSVP to free things just to save themselves a ticket, and then never show up
