### ISSUE TITLE
Contact people with details & survey

### ISSUE THREAD

**Issue by stefaniebutland** [KamloopsR/Meetup#5]

**Comment by chadfawcett** [comment]
@stefaniebutland I've made your requested changes to the survey. It should be good to share now! https://goo.gl/forms/vT69l33LHZLyioQw2

**Comment by stefaniebutland** [comment]
awesome thanks Chad. I'll prob get to this Thurs or Fri

**Comment by chadfawcett** [comment]
@stefaniebutland Any updates on this? Are you able to send it out? Alternatively I can post it to the Slack channels.

**Comment by stefaniebutland** [comment]
😬 I'll do this today. Took an offline break till today

**Comment by stefaniebutland** [comment]
done. @chadfawcett I guess when you see who has filled the survey you could individually ping people who expressed interest but didn't fill after a few days.

**Comment by kluft** [comment]
@chadfawcett  Would you be able to share the raw excel file with me? Or send me a csv? I would like to look through peoples motivations and see if I can find tutorials that match up with what people want to do.
